# Generated by Django 2.2.4 on 2019-09-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0004_auto_20190820_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stream',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listener.Station'),
        ),
    ]
