# Generated by Django 3.2.13 on 2022-06-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0008_auto_20191209_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listener',
            options={'ordering': ('-session',)},
        ),
    ]
