# Generated by Django 3.2.14 on 2022-08-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listener', '0009_alter_listener_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('connection', models.BooleanField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listener.stream')),
            ],
            options={
                'ordering': ('-timestamp', '-stream'),
            },
        ),
    ]
