# Generated by Django 3.2.14 on 2022-08-08 12:40

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listener', '0009_alter_listener_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disconnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listener.stream')),
            ],
            options={
                'ordering': ('-period', '-stream'),
            },
        ),
    ]
