# Generated by Django 4.1.1 on 2022-10-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listener", "0009_alter_listener_options"),
        ("source", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="listener.stream",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
